### PR TITLE
[MM-52657] AV1 support

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR adds support for encoding tracks using multiple codecs.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-52657

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Awesome, thanks for the simplification!

**Comment by streamer45** [comment]
I only merged, but I need to ask again... :smirk:

**Comment by streamer45** [comment]
No idea why it's failing.

**Comment by streamer45** [comment]
I'll defer to you @cpoile, I am out of clues other than trying to rebase and force push.

**Comment by streamer45** [comment]
What a pain :p

**Comment by streamer45** [comment]
@cpoile I think the CI may have been using the globally installed `tsc`, which may have been a different version. Now I am making sure we use the one from `node_modules` so the version doesn't randomly update when the Github runners do.

**Review by cpoile — APPROVED** [review]
Ahh, thanks!

**Pull request merged**
